export enum ContextoIdempotencyEnum {
    CADASTRAT_ESTOQUE = "CADASTRAR_ESTOQUE",
    CADASTRAR_FAMILIA = "CADASTRAR_FAMILIA",
    RECEBER_DOACAO = "RECEBER_DOACAO",
    GERAR_CESTA = "GERAR_CESTA",
    CADASTRAR_ACAO = "CADASTRAR_ACAO"
}