export enum PrioridadePesoEnum {
    MEMBRO_COM_PROBLEMA_SAUDE = 30,
    PESSOA_EMPREGADA = -10,
    AJUDA_RECEBIDA = 3,
    PESSOAS_POR_RESIDENCIA = 10,
    RECEBEU_AJUDA_COM_MAIS_30_DIAS = 15,
    RECEBEU_AJUDA_COM_MENOS_30_DIAS = -5,
}