openapi: 3.0.3
info:
  title: Backend Pastoral Social
  description: Modelo de Swagger com autenticação Bearer Token
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Servidor local de desenvolvimento

paths:
  /security/login:
    post:
      tags:
        - Security
      summary: Login do usuário
      description: Retorna um token Opaque Token para autenticação
      requestBody:
        $ref: '#/components/requestBodies/reqLoginDTO'
      responses:
        '200':
          $ref: '#/components/responses/resLoginResponseDTO'

  /security/refresh/token:
    post:
      tags:
        - Security
      summary: Refresh Token
      description: Retorna um novo token de acesso e refresh token
      requestBody:
        $ref: '#/components/requestBodies/reqRefreshTokenDTO'
      responses:
        '200':
          $ref: '#/components/responses/resRefreshTokenDTO'


  /estoque/cadastrar:
    post:
      tags:
        - Estoque
      summary: Cadastrar Estoque
      security:
        - BearerAuth: []
      description: Cadastra um novo estoque
      requestBody:
        $ref: '#/components/requestBodies/reqCadastrarEstoqueDTO'
      responses:
        '204':
          description: Estoque cadastrado com sucesso

  /estoque/consulta-geracao-template:
    post:
      tags:
        - Estoque
      security:
        - BearerAuth: []
      summary: Consultar disponibilidade para geração de modelo template
      description: Consultar disponibilidade modelo template
      requestBody:
        $ref: '#/components/requestBodies/reqConsultaGeracaoModeloTemplateDTO'
      responses:
        '200':
          $ref: '#/components/responses/resConsultaGeracaoModeloTemplateDTO'
  
  /estoque/geracao-modelo-template:
    post:
      tags:
        - Estoque
      security:
        - BearerAuth: []
      summary: Gerar modelo template
      description: Gerar modelo template
      requestBody:
        $ref: '#/components/requestBodies/reqGerarModeloTemplateDTO'
      responses:
        '200':
          $ref: '#/components/responses/resGerarModeloTemplateDTO'

  /und-medidas/listas:
    get:
      tags:
        - Estoque
      security:
        - BearerAuth: []
      summary: Listar unidade de medidas
      description: Lista unidade de medidas
      responses:
        '200':
          $ref: '#/components/responses/resListaUnidadeMedidasDTO'

  /estoque/localizacao/listar:
    get:
      tags:
        - Estoque
      security:
        - BearerAuth: []
      summary: Listar localização de produtos
      description: Lista as localizações dos produtos
      responses:
        '200':
          $ref: '#/components/responses/resListaLocalizacaoDTO'
  
  /familia/cadastrar:
    post:
      tags:
        - Familia
      security:
        - BearerAuth: []
      summary: Cadastrar familia
      description: Cadastra familia
      requestBody:
        $ref: '#/components/requestBodies/reqCadastrarFamiliaDTO'
      responses:
        '204':
          description: Estoque cadastrado com sucesso

  /dificuldade/listar:
    get:
      tags:
        - Familia
      security:
        - BearerAuth: []
      summary: Listar dificuldades
      description: Listar dificuldades
      responses:
        '200':
          $ref: '#/components/responses/resListarDificuldadesDTO'

  /template/lista:
    get:
      tags:
        - Template
      security:
        - BearerAuth: []
      summary: Listar templates
      description: Listagem paginada dos templates
      responses:
        '200':
          $ref: '#/components/responses/resListarTemplatesPaginadosDTO'
  
  /estoque/listar:
    get:
      tags:
        - Estoque
      security:
        - BearerAuth: []
      summary: Listar estoque
      description: Listagem de estoque
      responses:
        '200':
          $ref: '#/components/responses/resListarEstoqueDTO'


components:
  requestBodies:
    reqCadastrarFamiliaDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CadastrarFamiliaDTO'

    reqLoginDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginDTO'

    reqCadastrarEstoqueDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CadastrarEstoqueDTO'

    reqRefreshTokenDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RefreshTokenDTO'

    reqConsultaGeracaoModeloTemplateDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConsultaGeracaoTemplateDTO'

    reqGerarModeloTemplateDTO:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GerarModeloTemplateDTO'
  
  responses:
    resListarEstoqueDTO:
      description: Listar estoque
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ListarEstoqueDTO'
            required:
              - statusCode
              - timestamp
              - data
    resListarTemplatesPaginadosDTO:
      description: Listar templates paginados
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/PaginatedTemplatesDTO'
            required:
              - statusCode
              - timestamp
              - data
    resListarDificuldadesDTO:
      description: Listar dificuldades
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ListarDificuldadesDTO'
            required:
              - statusCode
              - timestamp
              - data
    resLoginResponseDTO:
      description: Login realizado com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/LoginResponseDTO'
            required:
              - statusCode
              - timestamp
              - data

    resRefreshTokenDTO:
      description: Requisição realizada com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ResponseRefreshTokenDTO'
            required:
              - statusCode
              - timestamp
              - data

    resConsultaGeracaoModeloTemplateDTO:
      description: Modelo template consultado com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ResponseConsultaGeracaoModeloTemplateDTO'
            required:
              - statusCode
              - timestamp
              - data

    resGerarModeloTemplateDTO:
      description: Modelo template gerado com sucesso
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ResponseGeracaoModeloTemplateDTO'
            required:
              - statusCode
              - timestamp
              - data

    resListaUnidadeMedidasDTO:
      description: Lista Unidade de Medidas
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ResponseListaUnidadeMedidasDTO'
            required:
              - statusCode
              - timestamp
              - data

    resListaLocalizacaoDTO:
      description: Lista localização dos produtos
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 200
              timestamp:
                type: string
                format: date-time
                example: "2025-09-21T16:42:22.818Z"
              data:
                $ref: '#/components/schemas/ResponseListaLocalizacaoDTO'
            required:
              - statusCode
              - timestamp
              - data
            

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Opaque Token

  schemas:
    ListarEstoqueDTO:
      type: array
      items:
        type: object
        properties:
          idEstoque:
            type: number
          validade:
            type: string
            format: date
            example: '2025-08-22'
          entrada:
            type: string
            format: date
          saida:
            type: string
            format: date
          itemProduto:
            $ref: '#/components/schemas/ItemProdutoDTO'
          localizacao:
            $ref: '#/components/schemas/LocalizacaoDTO'
          unidadeDeMedida:
            $ref: '#/components/schemas/UnidadeDeMedidaDTO'
        required:
          - idEstoque
          - validade
          - entrada
          - itemProduto
          - localizacao
          - unidadeDeMedida
    UnidadeDeMedidaDTO:
      type: object
      properties:
        idUnidadeDeMedida:
          type: number
        descricao:
          type: string
      required:
        - idUnidadeDeMedida
        - descricao
    LocalizacaoDTO:
      type: object
      properties:
        idLocalizacao:
          type: number
        descricao:
          type: string
      required:
        - idLocalizacao
        - descricao
    ItemProdutoDTO:
      type: object
      properties:
        idItemProduto:
          type: number
        descricao:
          type: string
      required:
        - idItemProduto
        - descricao
    PaginatedTemplatesDTO:
      type: object
      properties:
        paginaAtual:
          type: number
        totalItens:
          type: number
        totalPaginas:
          type: number
        result: 
          type: object
          properties:
            idTemplate:
              type: number
            descricao:  
              type: string
            qtdPossivelGeracao:
              type: number
          required:
            - idTemplate
            - descricao
            - qtdPossivelGeracao
      required:
        - paginaAtual
        - totalItens
        - totalPaginas
        - result
    ListarDificuldadesDTO:
      type: array
      items:
        type: object
        properties:
          idDificuldade:
            type: number
          descricao:
            type: string
        required:
          - idDificuldade
          - descricao
    CadastrarFamiliaDTO:
      type: object
      properties:
        nomeRepresentante:
          type: string
        idade: 
          type: number
        idComunidade:
          type: number
        idDificuldade:
          type: number
        cpfRg:
          type: string
        telefone:
          type: string
        endereco:
          type: string
        qtdPessoasResidencia:
          type: number
        qtdPessoasEmpregadas:
          type: number
        criancasFrequentamEscola:
          type: boolean
        membroComProblemaSaude:
          type: boolean
        jaRecebeuAjuda:
          type: boolean
        desejaParticiparCursos:
          type: boolean
        observacao:
          type: string
        outros:
          type: string
      required:
        - nomeRepresentante
        - idade
        - idComunidade
        - idDificuldade
      
    ResponseRefreshTokenDTO:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken

    RefreshTokenDTO:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken

    LoginDTO:
      type: object
      properties:
        nickName:
          type: string
          example: thiago@example.com
        senha:
          type: string
          example: senha123
      required:
        - nickName
        - senha

    LoginResponseDTO:
      type: object
      properties:
        user: 
          $ref: '#/components/schemas/UserDTO'
        security:
          $ref: '#/components/schemas/PermissinSecurityDTO'
    
    UserDTO:
      type: object
      properties: 
        userId:
          type: number
          example: 1231
        nickName:
          type: string
        permissions:
          type: array
          items:
            type: string
            example: ["cadastrar_familia", "cadastrar_item_estoque"]
      required:
        - userId
        - nickName
        - permissions

    PermissinSecurityDTO:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
        - refreshToken

    CadastrarEstoqueDTO:
      type: object
      properties:
        validade:
          type: string
          example: "2025-09-21"
          format: date
        itemProdutoId:
          type: number
          example: 12345
        idLocalizacao:
          type: number
          example: 12345
        idUnidadeMedida:
          type: number
          example: 12345
      required:
        - validade
        - itemProdutoId
        - idLocalizacao
        - idUnidadeMedida

    ConsultaGeracaoTemplateDTO:
      type: object
      properties:
        templateItens:
          type: array
          items:
            type: object
            properties:
              itemProdutoId:
                type: number
              quantidade:
                type: number
            required:
              - itemProdutoId
              - quantidade
      required:
        - templateItens

    ResponseConsultaGeracaoModeloTemplateDTO:
      type: object
      properties:
        quantidadePossivel:
          type: number
          example: 50
      required:
        - quantidadePossivel

    ResponseGeracaoModeloTemplateDTO:
      type: object
      properties:
        templateId:
          type: number
          example: 124
      required:
        - templateId

    GerarModeloTemplateDTO:
      type: object
      properties:
        qtdGeracaoPossivel:
          type: number
          example: 50
        template:
          $ref: '#/components/schemas/CriarTemplateDTO'
        templateItens:
          $ref: '#/components/schemas/TemplateItemDTO'
      required:
        - qtdGeracaoPossivel
        - template
        - templateItens

    TemplateItemDTO:
      type: array
      items:
        type: object
        properties:
          itemProdutoId:
            type: number
            example: 1414
          quantidade:
            type: number
        required:
          - itemProdutoId
          - quantidade
        

    CriarTemplateDTO:
      type: object
      properties:
        templateDesc:
          type: string
        templateType:
          type: string
          enum: ['CESTA_BASICA', 'JANTA', 'ALMOCO']
        gerarCestas:
          type: boolean
          description: "Campo opcional utilizado para gerar cestas básicas também"
      required:
        - templateDesc
        - templateType

    ResponseListaUnidadeMedidasDTO:
      type: array
      items:
        type: object
        properties:
          idUnidadeDeMedida:
            type: number
          descricao:
            type: string
        required:
          - idUnidadeDeMedida
          - descricao

    ResponseListaLocalizacaoDTO:
      type: array
      items:
        type: object
        properties:
          idLocalizacao:  
            type: number
          descricao:
            type: string
        required:
          - idLocalizacao
          - descricao


  


