import { Auth } from "./adapters/http/authentication/Auth";
import { Authorize } from "./adapters/http/authorization/Authorize";
import { ExpressAdapter } from "./adapters/http/ExpressAdapter"
import { MainController } from "./adapters/controller/MainController";
import { PostgresDatabase } from "./adapters/persistence/database/PostgresDatabase";
import { EstoqueService } from "./application/service/EstoqueService";
import { EstoqueController } from "./adapters/controller/EstoqueController";
import { EstoquePostgresDatabase } from "./adapters/persistence/EstoquePostgresDatabase";
import { AbilityPermission } from "./adapters/http/authorization/Permission";
import { RolePermissionsPostgresDatabase } from "./adapters/persistence/RolePermissionsPostgresDatabase";
import { FamiliaController } from "./adapters/controller/FamiliaController";
import { FamiliaPostgresDatabase } from "./adapters/persistence/FamiliaPostgresDatabase";
import { FamiliaService } from "./application/service/FamiliaService";
import { AuthService } from "./application/service/AuthService";
import { UserPostgresDatabase } from "./adapters/persistence/UserPostgresDatabase";
import { SecurityPostgresDatabase } from "./adapters/persistence/SecurityPostgresDatabase";
import { AuthPostgresDatabase } from "./adapters/persistence/AuthPostgresDatabase";
import { TemplatePostgresDatabase } from "./adapters/persistence/TemplatePostgresDatabase";
import { AcaoSocialTemplatePostgresDatabase } from "./adapters/persistence/AcaoSocialTemplatePostgresDatabase";
import { ItemTemplatePostgresDatabase } from "./adapters/persistence/ItemTemplatePostgresDatabase";
import { UnitOfWorkAdapter } from "./adapters/persistence/unitOfWork/UnitOfWorkAdapter";
import { config } from 'dotenv';
config();

(async () => {
    const postgresDatabase = new PostgresDatabase();
    await postgresDatabase.init();
    const httpClient = new ExpressAdapter();
    const unitOfWork = new UnitOfWorkAdapter(postgresDatabase);
    const roleRepository = new RolePermissionsPostgresDatabase(postgresDatabase);
    const estoquePostgres = new EstoquePostgresDatabase(postgresDatabase, unitOfWork);
    const familiaRepository = new FamiliaPostgresDatabase(postgresDatabase);
    const userRepository = new UserPostgresDatabase(postgresDatabase);
    const securityRepository = new SecurityPostgresDatabase(postgresDatabase);
    const authRepository = new AuthPostgresDatabase(postgresDatabase);
    const templateRepository = new TemplatePostgresDatabase(postgresDatabase);
    const acaoSocialTemplate = new AcaoSocialTemplatePostgresDatabase(postgresDatabase, unitOfWork);
    const itemTemplateRepository = new ItemTemplatePostgresDatabase(postgresDatabase, unitOfWork);
    const abilityPermission = new AbilityPermission(roleRepository);
    await abilityPermission.setupPermissions();
    const estoqueService = new EstoqueService(estoquePostgres, acaoSocialTemplate, itemTemplateRepository, templateRepository, unitOfWork);
    const familiaUseCase = new FamiliaService(familiaRepository);
    const authUseCase = new AuthService(userRepository, securityRepository, authRepository);
    const auth = new Auth(authRepository);
    const authorize = new Authorize(abilityPermission.getAppAbility());
    new MainController(httpClient, authUseCase);
    new EstoqueController(httpClient, auth, authorize, estoqueService);
    new FamiliaController(httpClient, auth, authorize, familiaUseCase);
    const PORT = parseInt(process.env.PORT as string);
    httpClient.listen(PORT, () => console.log(`Rodando na porta: ${PORT}`));
})()