import "reflect-metadata";
import { CronJob } from "cron";
import { Auth } from "./adapters/http/authentication/Auth";
import { Authorize } from "./adapters/http/authorization/Authorize";
import { ExpressAdapter } from "./adapters/http/ExpressAdapter"
import { MainController } from "./adapters/controller/MainController";
import { PostgresDatabase } from "./adapters/persistence/database/PostgresDatabase";
import { EstoqueService } from "./application/service/EstoqueService";
import { EstoqueController } from "./adapters/controller/EstoqueController";
import { EstoquePostgresDatabase } from "./adapters/persistence/EstoquePostgresDatabase";
import { AbilityPermission } from "./adapters/http/authorization/Permission";
import { RolePermissionsPostgresDatabase } from "./adapters/persistence/RolePermissionsPostgresDatabase";
import { FamiliaController } from "./adapters/controller/FamiliaController";
import { FamiliaPostgresDatabase } from "./adapters/persistence/FamiliaPostgresDatabase";
import { ConsultarFamiliaService } from "./application/service/ConsultarFamiliaService";
import { AuthService } from "./application/service/AuthService";
import { UsuarioPostgresDatabase } from "./adapters/persistence/UsuarioPostgresDatabase";
import { SecurityPostgresDatabase } from "./adapters/persistence/SecurityPostgresDatabase";
import { AuthPostgresDatabase } from "./adapters/persistence/AuthPostgresDatabase";
import { TemplatePostgresDatabase } from "./adapters/persistence/TemplatePostgresDatabase";
import { ItemTemplatePostgresDatabase } from "./adapters/persistence/ItemTemplatePostgresDatabase";
import { UnitOfWorkAdapter } from "./adapters/persistence/unitOfWork/UnitOfWorkAdapter";
import { TemplateController } from "./adapters/controller/TemplateController";
import { TemplateService } from "./application/service/TemplateService";
import { FamiliaAuditProxy } from "./application/proxy/FamiliaAuditProxy";
import { CadastrarFamiliaService } from "./application/service/CadastrarFamiliaService";
import { AuditoriaPostgresDatabase } from "./adapters/persistence/AuditoriaPostgresDatabase";
import { GerarModeloTemplateProxy } from "./application/proxy/GerarModeloTemplateProxy";
import { loggerAdapter, loggerHTTP } from './adapters/logger';
import { CestaGeradaPostgresDatabase } from "./adapters/persistence/CestaGeradaPostgresDatabase";
import { CestasController } from "./adapters/controller/CestasController";
import { GerarCestasService } from "./application/service/GerarCestasService";
import { AjudaController } from "./adapters/controller/AjudaController";
import { AssociarFamiliaAjudaService } from "./application/service/AssociarFamiliaAjudaService";
import { AjudaRecebidaPostgresDatabase } from "./adapters/persistence/AjudaRecebidaPostgresDatabase";
import { GetFamiliaService } from "./application/service/GetFamiliaService";
import { NotificacaoWhatsAppGatewayImpl } from "./adapters/http/gateway/NotificacaoWhatsAppGatewayImpl";
import { NotificacaoProdutoVencidoService } from "./application/service/NotificacaoProdutoVencidoService";
import { GetCestasService } from "./application/service/GetCestasService";
import { CancelarCestaService } from "./application/service/CancelarCestaService";
import { CestaEstoqueItemPostgresDatabase } from "./adapters/persistence/CestaEstoqueItemPostgresDatabase";
import { ListarTemplatesComCestasDisponiveisService } from "./application/service/ListarTemplatesComCestasDisponiveisService";
import { UsuarioController } from "./adapters/controller/UsuarioController";
import { UpdateUsuarioService } from "./application/service/UpdateUsuarioService";
import { CancelarAjudaService } from "./application/service/CancelarAjudaService";
import { ListarAjudasService } from "./application/service/ListarAjudasService";
import { LocalizacaoPostgresDatabase } from "./adapters/persistence/LocalizacaoPostgresDatabase";
import { config } from 'dotenv';
import { WebhookWhatsappController } from "./adapters/controller/WebhookWhatsappController";
import { HealthCheckController } from "./adapters/controller/HealthcheckController";
import { AcaoController } from "./adapters/controller/AcaoController";
import { AcaoPostgresDatabase } from "./adapters/persistence/AcaoPostgresDatabase";
import { AcaoService } from "./application/service/AcaoService";
import { DoacaoPostgresDatabase } from "./adapters/persistence/DoacaoPostgresDatabase";
import { DoadorPostgresDatabase } from "./adapters/persistence/DoadorPostgresDatabase";
import { DoacaoService } from "./application/service/DoacaoService";
import { DoacaoController } from "./adapters/controller/DoacaoController";
import { IdempotenciaPostgresDatabase } from "./adapters/persistence/IdempotenciaPostgresDatabase";
import { IdempotenciaService } from "./application/service/IdempotenciaService";
config();

export async function buildApp() {
    const logger = loggerAdapter;
    const postgresDatabase = new PostgresDatabase();
    await postgresDatabase.init();
    const httpClient = new ExpressAdapter(loggerHTTP);
    const unitOfWork = new UnitOfWorkAdapter(logger, postgresDatabase);
    const roleRepository = new RolePermissionsPostgresDatabase(postgresDatabase);
    const estoqueRepositiory = new EstoquePostgresDatabase(postgresDatabase, unitOfWork);
    const familiaRepository = new FamiliaPostgresDatabase(logger, postgresDatabase, unitOfWork);
    const usuarioRepository = new UsuarioPostgresDatabase(logger, postgresDatabase);
    const securityRepository = new SecurityPostgresDatabase(postgresDatabase);
    const authRepository = new AuthPostgresDatabase(postgresDatabase);
    const templateRepository = new TemplatePostgresDatabase(logger, postgresDatabase, unitOfWork);
    const auditoriaRepository = new AuditoriaPostgresDatabase(postgresDatabase, logger);
    const itemTemplateRepository = new ItemTemplatePostgresDatabase(logger, unitOfWork);
    const cestaGeradaRepository = new CestaGeradaPostgresDatabase(logger, postgresDatabase, unitOfWork);
    const ajudaRepository = new AjudaRecebidaPostgresDatabase(logger, postgresDatabase, unitOfWork);
    const acaoRepository = new AcaoPostgresDatabase(postgresDatabase, unitOfWork);
    const cestaEstoqueItemRepository = new CestaEstoqueItemPostgresDatabase(logger, unitOfWork);
    const localizacaoRepository = new LocalizacaoPostgresDatabase(postgresDatabase, unitOfWork);
    const doacaoRepository = new DoacaoPostgresDatabase(postgresDatabase, unitOfWork);
    const idempotenciaRepository = new IdempotenciaPostgresDatabase(postgresDatabase);
    const doadorRepository = new DoadorPostgresDatabase(postgresDatabase, unitOfWork);
    const abilityPermission = new AbilityPermission(roleRepository);
    await abilityPermission.setupPermissions();
    const estoqueService = new EstoqueService(logger, estoqueRepositiory, itemTemplateRepository, templateRepository, cestaGeradaRepository, cestaEstoqueItemRepository, localizacaoRepository, unitOfWork);
    const gerarCestasService = new GerarCestasService(logger, templateRepository, cestaGeradaRepository, estoqueRepositiory, cestaEstoqueItemRepository, estoqueService, unitOfWork);
    const templateService = new TemplateService(templateRepository, estoqueService);
    const consultarFamiliaService = new ConsultarFamiliaService(familiaRepository);
    const cadastrarFamiliaService = new CadastrarFamiliaService(logger, familiaRepository, unitOfWork);
    const cancelarAjudaService = new CancelarAjudaService(logger, ajudaRepository, unitOfWork);
    const notificacaoWhatsAppGateway = new NotificacaoWhatsAppGatewayImpl();
    const notificacaoProdutoVencidoService = new NotificacaoProdutoVencidoService(notificacaoWhatsAppGateway);
    const getFamiliaService = new GetFamiliaService(familiaRepository);
    const getCestasService = new GetCestasService(logger, cestaGeradaRepository);
    const updateUsuarioService = new UpdateUsuarioService(logger, usuarioRepository);
    const listarAjudasService = new ListarAjudasService(logger, ajudaRepository);
    const idempotenciaService = new IdempotenciaService(idempotenciaRepository);
    const doacaoService = new DoacaoService(logger, unitOfWork, doadorRepository, doacaoRepository, idempotenciaService);
    const listarTemplatesComCestasDisponiveisService = new ListarTemplatesComCestasDisponiveisService(logger, templateRepository);
    const cancelarCestaService = new CancelarCestaService(logger, cestaGeradaRepository, ajudaRepository, estoqueRepositiory, unitOfWork);
    const associarAjudaFamiliaService = new AssociarFamiliaAjudaService(logger, cestaGeradaRepository, ajudaRepository, familiaRepository, unitOfWork);
    const familiaAuditProxy = new FamiliaAuditProxy(cadastrarFamiliaService, auditoriaRepository);
    const gerarModeloTemplateProxy = new GerarModeloTemplateProxy(logger, estoqueService, auditoriaRepository);
    const acaoService = new AcaoService(estoqueService, acaoRepository, unitOfWork, logger);
    const authUseCase = new AuthService(logger, usuarioRepository, securityRepository, authRepository);
    const auth = new Auth(authRepository);
    const authorize = new Authorize(abilityPermission.getAppAbility());
    new TemplateController(httpClient, auth, authorize, templateService, listarTemplatesComCestasDisponiveisService);
    new MainController(httpClient, authUseCase);
    new EstoqueController(httpClient, auth, authorize, estoqueService, gerarModeloTemplateProxy);
    new FamiliaController(httpClient, auth, authorize, familiaAuditProxy, consultarFamiliaService, getFamiliaService);
    new CestasController(httpClient, auth, authorize, gerarCestasService, getCestasService, cancelarCestaService);
    new AjudaController(httpClient, auth, authorize, associarAjudaFamiliaService, cancelarAjudaService, listarAjudasService);
    new UsuarioController(httpClient, auth, authorize, updateUsuarioService);
    new WebhookWhatsappController(httpClient);
    new HealthCheckController(httpClient);
    new DoacaoController(httpClient, auth, authorize, doacaoService);
    new AcaoController(httpClient, auth, authorize, acaoService);
    const notificaProdutoVencidoJob = new CronJob('* * * * *', async () => await notificacaoProdutoVencidoService.execute() );
    // notificaProdutoVencidoJob.start();
    return httpClient.getExpress();
}