import { CronJob } from "cron";
import { Auth } from "./adapters/http/authentication/Auth";
import { Authorize } from "./adapters/http/authorization/Authorize";
import { ExpressAdapter } from "./adapters/http/ExpressAdapter"
import { MainController } from "./adapters/controller/MainController";
import { PostgresDatabase } from "./adapters/persistence/database/PostgresDatabase";
import { EstoqueService } from "./application/service/EstoqueService";
import { EstoqueController } from "./adapters/controller/EstoqueController";
import { EstoquePostgresDatabase } from "./adapters/persistence/EstoquePostgresDatabase";
import { AbilityPermission } from "./adapters/http/authorization/Permission";
import { RolePermissionsPostgresDatabase } from "./adapters/persistence/RolePermissionsPostgresDatabase";
import { FamiliaController } from "./adapters/controller/FamiliaController";
import { FamiliaPostgresDatabase } from "./adapters/persistence/FamiliaPostgresDatabase";
import { ConsultarFamiliaService } from "./application/service/ConsultarFamiliaService";
import { AuthService } from "./application/service/AuthService";
import { UserPostgresDatabase } from "./adapters/persistence/UserPostgresDatabase";
import { SecurityPostgresDatabase } from "./adapters/persistence/SecurityPostgresDatabase";
import { AuthPostgresDatabase } from "./adapters/persistence/AuthPostgresDatabase";
import { TemplatePostgresDatabase } from "./adapters/persistence/TemplatePostgresDatabase";
import { AcaoSocialTemplatePostgresDatabase } from "./adapters/persistence/AcaoSocialTemplatePostgresDatabase";
import { ItemTemplatePostgresDatabase } from "./adapters/persistence/ItemTemplatePostgresDatabase";
import { UnitOfWorkAdapter } from "./adapters/persistence/unitOfWork/UnitOfWorkAdapter";
import { TemplateController } from "./adapters/controller/TemplateController";
import { TemplateService } from "./application/service/TemplateService";
import { FamiliaAuditProxy } from "./application/proxy/FamiliaAuditProxy";
import { CadastrarFamiliaService } from "./application/service/CadastrarFamiliaService";
import { AuditoriaPostgresDatabase } from "./adapters/persistence/AuditoriaPostgresDatabase";
import { GerarModeloTemplateProxy } from "./application/proxy/GerarModeloTemplateProxy";
import { loggerAdapter, loggerHTTP } from './adapters/logger';
import { CestaGeradaPostgresDatabase } from "./adapters/persistence/CestaGeradaPostgresDatabase";
import { GerarCestasController } from "./adapters/controller/GerarCestasController";
import { GerarCestasService } from "./application/service/GerarCestasService";
import { AjudaController } from "./adapters/controller/AjudaController";
import { AssociarFamiliaAjudaService } from "./application/service/AssociarFamiliaAjudaService";
import { AjudaRecebidaPostgresDatabase } from "./adapters/persistence/AjudaRecebidaPostgresDatabase";
import { GetFamiliaService } from "./application/service/GetFamiliaService";
import { config } from 'dotenv';
config();

(async () => {
    const logger = loggerAdapter;
    const postgresDatabase = new PostgresDatabase();
    await postgresDatabase.init();
    const httpClient = new ExpressAdapter(loggerHTTP);
    const unitOfWork = new UnitOfWorkAdapter(logger, postgresDatabase);
    const roleRepository = new RolePermissionsPostgresDatabase(postgresDatabase);
    const estoquePostgres = new EstoquePostgresDatabase(postgresDatabase, unitOfWork);
    const familiaRepository = new FamiliaPostgresDatabase(postgresDatabase);
    const userRepository = new UserPostgresDatabase(postgresDatabase);
    const securityRepository = new SecurityPostgresDatabase(postgresDatabase);
    const authRepository = new AuthPostgresDatabase(postgresDatabase);
    const templateRepository = new TemplatePostgresDatabase(logger, postgresDatabase, unitOfWork);
    const auditoriaRepository = new AuditoriaPostgresDatabase(postgresDatabase, logger);
    const acaoSocialTemplate = new AcaoSocialTemplatePostgresDatabase(logger, unitOfWork);
    const itemTemplateRepository = new ItemTemplatePostgresDatabase(logger, unitOfWork);
    const cestaGeradaRepository = new CestaGeradaPostgresDatabase(logger, postgresDatabase, unitOfWork);
    const ajudaRepository = new AjudaRecebidaPostgresDatabase(logger, postgresDatabase);
    const abilityPermission = new AbilityPermission(roleRepository);
    await abilityPermission.setupPermissions();
    const estoqueService = new EstoqueService(logger, estoquePostgres, acaoSocialTemplate, itemTemplateRepository, templateRepository, cestaGeradaRepository, unitOfWork);
    const templateService = new TemplateService(templateRepository, estoqueService);
    const consultarFamiliaService = new ConsultarFamiliaService(familiaRepository);
    const cadastrarFamiliaService = new CadastrarFamiliaService(logger, familiaRepository);
    const getFamiliaService = new GetFamiliaService(familiaRepository);
    const gerarCestasService = new GerarCestasService(logger, templateRepository, cestaGeradaRepository, estoqueService);
    const associarAjudaFamiliaService = new AssociarFamiliaAjudaService(logger, ajudaRepository, cestaGeradaRepository, familiaRepository);
    const familiaAuditProxy = new FamiliaAuditProxy(cadastrarFamiliaService, auditoriaRepository);
    const gerarModeloTemplateProxy = new GerarModeloTemplateProxy(logger, estoqueService, auditoriaRepository);
    const authUseCase = new AuthService(logger, userRepository, securityRepository, authRepository);
    const auth = new Auth(authRepository);
    const authorize = new Authorize(abilityPermission.getAppAbility());
    new TemplateController(httpClient, templateService);
    new MainController(httpClient, authUseCase);
    new EstoqueController(httpClient, auth, authorize, estoqueService, gerarModeloTemplateProxy);
    new FamiliaController(httpClient, auth, authorize, familiaAuditProxy, consultarFamiliaService, getFamiliaService);
    new GerarCestasController(httpClient, auth, authorize, gerarCestasService);
    new AjudaController(httpClient, auth, authorize, associarAjudaFamiliaService);
    const notificaProdutoVencidoJob = new CronJob('* * * * *', async () => console.log("=============>>>>>>>>>>>>>>>> Executou") );
    notificaProdutoVencidoJob.start();
    const PORT = parseInt(process.env.PORT as string);
    httpClient.listen(PORT, () => console.log(`Rodando na porta: ${PORT}`));
})()